[project]
name = "recipe-index"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymupdf>=1.26.7",
    "pytest>=9.0.2",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.45",
]
